services:
#  rabbitmq:
#    image: rabbitmq:management
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  postgres:
    container_name: monitoring_postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    ports:
      - "5430:5432"
